version: '3.8'

services:
  message_processor-server:
    image: message_processor:latest
    volumes:
      - ./media_archive:/app/media_archive
    networks:
      - message_processor-network

networks:
  message_processor-network:
    driver: bridge